name: Build Finance Pro

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm init -y && npm install electron electron-builder --save-dev

    - name: Create main.js
      run: |
        echo const { app, BrowserWindow } = require('electron')
        echo function createWindow () {
        echo   const win = new BrowserWindow({ width: 1280, height: 800 })
        echo   win.loadFile('index.html')
        echo   win.setMenu(null)
        echo }
        echo app.whenReady().then(createWindow)
        echo app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() }) > main.js

    - name: Build .exe
      run: npx electron-builder --win

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.exe
